#!/bin/bash

# Comprehensive Icon Sets Test for Nerd Fonts
# Tests all major icon categories with labels

# Color codes
RESET='\033[0m'
BOLD='\033[1m'
FG_CYAN='\033[1;36m'
FG_YELLOW='\033[1;33m'
FG_GREEN='\033[1;32m'
FG_BLUE='\033[1;34m'
FG_MAGENTA='\033[1;35m'
FG_RED='\033[1;31m'

print_section() {
    local title="$1"
    local color="${2:-$FG_CYAN}"
    echo ""
    printf "${color}${BOLD}%s${RESET}\n" "$title"
    printf "${color}%s${RESET}\n" "$(printf '─%.0s' {1..60})"
}

print_icon() {
    printf "  %-30s %s\n" "$1" "$2"
}

echo ""
printf "${BOLD}${FG_CYAN}╔════════════════════════════════════════════════════════════╗${RESET}\n"
printf "${BOLD}${FG_CYAN}║         Comprehensive Nerd Fonts Icon Test                ║${RESET}\n"
printf "${BOLD}${FG_CYAN}╚════════════════════════════════════════════════════════════╝${RESET}\n"

# Powerline Symbols
print_section "⚡ Powerline Symbols" "$FG_YELLOW"
print_icon "Branch:"                ""
print_icon "Line Number:"           ""
print_icon "Column:"                ""
print_icon "Lock:"                  ""
print_icon "Modified:"              ""
print_icon "Plus:"                  ""
print_icon "Right Arrow:"           ""
print_icon "Left Arrow:"            ""
print_icon "Right Filled:"          ""
print_icon "Left Filled:"           ""
print_icon "Right Thin:"            ""
print_icon "Left Thin:"             ""
print_icon "Flame:"                 ""
print_icon "Circle:"                ""

# File Types - Programming Languages
print_section "💻 Programming Languages" "$FG_GREEN"
print_icon "Assembly (.asm):"       ""
print_icon "C (.c):"                ""
print_icon "C++ (.cpp):"            ""
print_icon "C# (.cs):"              ""
print_icon "Clojure (.clj):"        ""
print_icon "CoffeeScript (.coffee):""
print_icon "Crystal (.cr):"         ""
print_icon "Dart (.dart):"          ""
print_icon "Elixir (.ex):"          ""
print_icon "Elm (.elm):"            ""
print_icon "Erlang (.erl):"         ""
print_icon "F# (.fs):"              ""
print_icon "Go (.go):"              ""
print_icon "Haskell (.hs):"         ""
print_icon "Java (.java):"          ""
print_icon "JavaScript (.js):"      ""
print_icon "Julia (.jl):"           ""
print_icon "Kotlin (.kt):"          ""
print_icon "Lua (.lua):"            ""
print_icon "Nim (.nim):"            ""
print_icon "Perl (.pl):"            ""
print_icon "PHP (.php):"            ""
print_icon "Python (.py):"          ""
print_icon "R (.r):"                ""
print_icon "Ruby (.rb):"            ""
print_icon "Rust (.rs):"            ""
print_icon "Scala (.scala):"        ""
print_icon "Swift (.swift):"        ""
print_icon "TypeScript (.ts):"      ""
print_icon "Zig (.zig):"            ""

# Web Development
print_section "🌐 Web Development" "$FG_BLUE"
print_icon "HTML (.html):"          ""
print_icon "CSS (.css):"            ""
print_icon "SCSS (.scss):"          ""
print_icon "SASS (.sass):"          ""
print_icon "Less (.less):"          ""
print_icon "Vue (.vue):"            "󰡄"
print_icon "React (.jsx):"          ""
print_icon "Angular:"               ""
print_icon "Svelte (.svelte):"      ""
print_icon "Webpack:"               "󰜫"
print_icon "Node.js:"               ""
print_icon "NPM:"                   ""
print_icon "Yarn:"                  ""

# Configuration Files
print_section "⚙️  Configuration Files" "$FG_MAGENTA"
print_icon "JSON (.json):"          ""
print_icon "JSONC (.jsonc):"        ""
print_icon "YAML (.yaml):"          ""
print_icon "TOML (.toml):"          ""
print_icon "XML (.xml):"            ""
print_icon "INI (.ini):"            ""
print_icon "ENV (.env):"            ""
print_icon "EditorConfig:"          ""
print_icon "Prettier:"              ""
print_icon "ESLint:"                "󰱺"
print_icon "Babel:"                 "󰨥"

# Shell & Scripts
print_section "🐚 Shell & Scripts" "$FG_GREEN"
print_icon "Bash (.sh):"            ""
print_icon "Zsh (.zsh):"            ""
print_icon "Fish (.fish):"          ""
print_icon "PowerShell (.ps1):"     ""
print_icon "Terminal:"              ""
print_icon "Tmux:"                  ""
print_icon "Vim (.vim):"            ""
print_icon "Neovim:"                ""

# Version Control
print_section "📦 Version Control & DevOps" "$FG_YELLOW"
print_icon "Git:"                   ""
print_icon "GitHub:"                ""
print_icon "GitLab:"                ""
print_icon "Bitbucket:"             ""
print_icon ".gitignore:"            ""
print_icon ".gitattributes:"        ""
print_icon "Git Modified:"          ""
print_icon "Git Diff:"              ""
print_icon "Docker:"                "󰡨"
print_icon "Dockerfile:"            "󰡨"
print_icon "Docker Compose:"        "󰡨"
print_icon "Kubernetes:"            "󱃾"
print_icon "Terraform (.tf):"       ""
print_icon "Vagrant:"               ""
print_icon "Ansible:"               ""
print_icon "Jenkins:"               ""

# Data & Databases
print_section "🗄️  Data & Databases" "$FG_CYAN"
print_icon "Database:"              ""
print_icon "SQL (.sql):"            ""
print_icon "SQLite:"                ""
print_icon "PostgreSQL:"            ""
print_icon "MySQL:"                 ""
print_icon "MongoDB:"               ""
print_icon "Redis:"                 ""
print_icon "GraphQL (.graphql):"    ""
print_icon "Prisma:"                ""

# Documentation
print_section "📝 Documentation & Text" "$FG_BLUE"
print_icon "Markdown (.md):"        ""
print_icon "README:"                ""
print_icon "Text (.txt):"           ""
print_icon "PDF (.pdf):"            ""
print_icon "LaTeX (.tex):"          ""
print_icon "Org Mode (.org):"       ""
print_icon "reStructuredText (.rst):""
print_icon "AsciiDoc (.adoc):"      ""

# Build Tools & Package Managers
print_section "🔧 Build Tools" "$FG_MAGENTA"
print_icon "Makefile:"              ""
print_icon "CMake:"                 ""
print_icon "Gradle:"                ""
print_icon "Maven:"                 ""
print_icon "Cargo.toml:"            ""
print_icon "package.json:"          ""
print_icon "Gemfile:"               ""
print_icon "requirements.txt:"      ""
print_icon "Pipfile:"               ""
print_icon "poetry:"                ""
print_icon "go.mod:"                ""

# Archives & Binary Files
print_section "📦 Archives & Binary" "$FG_YELLOW"
print_icon "ZIP (.zip):"            ""
print_icon "RAR (.rar):"            ""
print_icon "TAR (.tar):"            ""
print_icon "GZ (.gz):"              ""
print_icon "7z (.7z):"              ""
print_icon "Binary (.bin):"         ""
print_icon "Executable (.exe):"     ""
print_icon "Library (.so/.dll):"    ""

# Media Files
print_section "🎨 Media Files" "$FG_MAGENTA"
print_icon "Image:"                 ""
print_icon "PNG (.png):"            ""
print_icon "JPG (.jpg):"            ""
print_icon "GIF (.gif):"            ""
print_icon "SVG (.svg):"            ""
print_icon "ICO (.ico):"            ""
print_icon "Video:"                 ""
print_icon "Audio:"                 ""
print_icon "Font (.ttf/.otf):"      ""

# Special Icons
print_section "⭐ Special & System Icons" "$FG_CYAN"
print_icon "Home:"                  ""
print_icon "Folder:"                ""
print_icon "Open Folder:"           ""
print_icon "Folder Git:"            ""
print_icon "Folder Config:"         ""
print_icon "File:"                  ""
print_icon "Files:"                 ""
print_icon "Search:"                ""
print_icon "Settings/Gear:"         ""
print_icon "Wrench:"                ""
print_icon "Download:"              ""
print_icon "Upload:"                ""
print_icon "Cloud:"                 "󰅟"
print_icon "Check/Success:"         ""
print_icon "Cross/Error:"           ""
print_icon "Warning:"               ""
print_icon "Info:"                  ""
print_icon "Question:"              ""
print_icon "Bell/Notification:"     ""
print_icon "Fire:"                  ""
print_icon "Lightning:"             ""
print_icon "Star:"                  ""
print_icon "Heart:"                 ""
print_icon "Shield:"                "󰞀"
print_icon "Lock:"                  ""
print_icon "Unlock:"                ""
print_icon "Key:"                   ""
print_icon "Bookmark:"              ""
print_icon "Tag:"                   ""
print_icon "Clock:"                 ""
print_icon "Calendar:"              ""
print_icon "Comment:"               ""
print_icon "Bug:"                   ""
print_icon "Pencil/Edit:"           ""
print_icon "Trash:"                 ""
print_icon "Archive:"               ""
print_icon "Package:"               ""
print_icon "Refresh:"               ""
print_icon "Sync:"                  ""

# Weather Icons
print_section "🌤️  Weather Icons" "$FG_BLUE"
print_icon "Sun:"                   ""
print_icon "Moon:"                  ""
print_icon "Cloud:"                 ""
print_icon "Rain:"                  ""
print_icon "Snow:"                  ""
print_icon "Storm:"                 ""
print_icon "Wind:"                  ""
print_icon "Fog:"                   ""
print_icon "Celsius:"               ""
print_icon "Fahrenheit:"            ""

# Pomicons
print_section "🍎 Pomicons" "$FG_RED"
print_icon "Apple:"                 ""
print_icon "Lock:"                  ""
print_icon "Short Lock:"            ""
print_icon "Loop:"                  ""
print_icon "Clean:"                 ""
print_icon "Connected:"             ""
print_icon "Disconnected:"          ""
print_icon "Refresh:"               ""
print_icon "Time:"                  ""
print_icon "Tools:"                 ""
print_icon "Bug:"                   ""

# Linux Distributions (Font Logos)
print_section "🐧 Linux & OS Icons" "$FG_CYAN"
print_icon "Linux:"                 ""
print_icon "Ubuntu:"                ""
print_icon "Debian:"                ""
print_icon "Fedora:"                ""
print_icon "RedHat:"                ""
print_icon "CentOS:"                ""
print_icon "Arch:"                  ""
print_icon "Gentoo:"                ""
print_icon "Alpine:"                ""
print_icon "FreeBSD:"               ""
print_icon "Android:"               ""
print_icon "Apple:"                 ""
print_icon "Windows:"               ""

# Codicons (VS Code)
print_section "📟 Codicons (VS Code)" "$FG_BLUE"
print_icon "VS Code:"               ""
print_icon "Account:"               ""
print_icon "Beaker:"                ""
print_icon "Broadcast:"             ""
print_icon "Case Sensitive:"        ""
print_icon "Checklist:"             ""
print_icon "Chrome:"                ""
print_icon "Circle Filled:"         ""
print_icon "Circuit Board:"         ""
print_icon "Code:"                  ""
print_icon "Color Mode:"            ""
print_icon "Compass:"               ""
print_icon "Copy:"                  ""
print_icon "Database:"              ""
print_icon "Debug:"                 ""
print_icon "Extensions:"            ""
print_icon "Gear:"                  ""
print_icon "Graph:"                 ""
print_icon "Law:"                   ""
print_icon "Library:"               ""
print_icon "Link:"                  ""
print_icon "Mention:"               ""
print_icon "Regex:"                 ""
print_icon "Remote:"                ""
print_icon "Report:"                ""
print_icon "Rocket:"                ""
print_icon "Server:"                ""
print_icon "Symbol Array:"          ""
print_icon "Symbol Class:"          ""
print_icon "Symbol Method:"         ""
print_icon "Symbol Variable:"       ""
print_icon "Telescope:"             ""
print_icon "Verified:"              ""
print_icon "Whole Word:"            ""

echo ""
print_section "✅ Test Complete" "$FG_GREEN"
printf "${FG_YELLOW}If you see boxes (□) or missing characters:${RESET}\n"
printf "  1. Install a Nerd Font: ${FG_CYAN}make install-fonts${RESET}\n"
printf "  2. Set your terminal font to a Nerd Font (e.g., 'Hack Nerd Font')\n"
printf "  3. Restart your terminal application\n"
echo ""
